from django.http import Http404
from django.shortcuts import get_object_or_404, render 
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import F
from django.urls import reverse
from .models import Question, Choice 
#  Use generic views:
from django.views import generic

def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list" : latest_question_list}
    return render(request, "polls/index.html", context)

"""
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    
    return render(request, "polls/detail.html", {"question" : question})
"""

#Shortcut : get_object_or_404()

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question":question})
    

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render( request, 
                   "polls/results.html", 
                   {"question":question} )

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,  
            "polls/detail.html",
            {
                "question" : question,
                "error_message" : "You didn't select a choice."
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevent data from being posted twice if a
        # user hits the Back button
        return HttpResponseRedirect( reverse("polls:results", args=(question.id,)) )


def showRequestObject(request):
    return HttpResponse(request)

#  Use generic views:
class IndexView(generic.ListView):
    """
       ListView generic view uses a default template 
    called <app name>/<model name>_list.html; we use 
    template_name to tell ListView to use our existing 
    "polls/index.html" template.
    """
    """
       we use template_name to tell ListView to use 
    our existing "polls/index.html" template.
    """
    template_name = "polls/index.html"

    """
      Django is able to determine an appropriate name for 
    the context variable. However, for ListView, the 
    automatically generated context variable is 
    question_list. To override this we provide the 
    context_object_name attribute, specifying that we 
    want to use latest_question_list instead.
    """
    context_object_name ="latest_question_list"

    # Each generic view needs to know what model it will be acting upon.
    # or by defining the get_queryset() method. 
    def get_queryset(self):
        """
          Return the last five published questions.
        """
        return Question.objects.order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    """
       By default, the DetailView generic view uses a template 
    called <app name>/<model name>_detail.html. In our case, 
    it would use the template "polls/question_detail.html". 
    """
    """
       The template_name attribute is used to tell Django to 
    use a specific template name instead of the autogenerated 
    default template name
    """    
    # Each generic view needs to know what model it will be acting upon.
    model = Question
    template_name = "polls/detail.html"
    """
       In previous parts of the tutorial, the templates have been 
    provided with a context that contains the question and 
    latest_question_list context variables. For DetailView the 
    question variable is provided automatically – since 
    we’re using a Django model (Question),
    """

class ResultsView(generic.DetailView):
    # Each generic view needs to know what model it will be acting upon.
    model = Question 
    template_name = "polls/results.html"